# Generated by Django 5.1.3 on 2024-11-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_user_profile_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='price',
            new_name='expirdate',
        ),
    ]
