# Generated by Django 5.1.3 on 2024-11-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_price_food_expirdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='expirdate',
            field=models.CharField(max_length=10),
        ),
    ]
