# Generated by Django 5.1.3 on 2024-11-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_food_expirdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='User',
            new_name='user',
        ),
    ]
